# actionlint configuration for rscrypto
# https://github.com/rhysd/actionlint/blob/main/docs/config.md

self-hosted-runner:
  labels:
    # Namespace custom runners (ARM64 Linux)
    - namespace-profile-rscrypto
    # Namespace perf runners (benchmarking)
    - namespace-profile-rscrypto-perf
    - namespace-profile-rscrypto-perf-arm
    # Warpbuild custom runners (various sizes)
    - warp-ubuntu-latest-x64-32x
    - warp-ubuntu-latest-x64-16x
    - warp-ubuntu-latest-x64-8x
    - warp-ubuntu-latest-x64-4x
    - warp-ubuntu-latest-x64-2x
