# actionlint configuration for rscrypto
# https://github.com/rhysd/actionlint/blob/main/docs/config.md

self-hosted-runner:
  labels:
    # Namespace runners
    - namespace-profile-rscrypto
    - namespace-profile-rscrypto-linux-x86
    - namespace-profile-rscrypto-linux-arm64

    # RunsOn benchmark/tune runners
    - runs-on=${{ github.run_id }}/runner=intel-spr
    - runs-on=${{ github.run_id }}/runner=intel-icl
    - runs-on=${{ github.run_id }}/runner=amd-zen4
    - runs-on=${{ github.run_id }}/runner=amd-zen5
    - runs-on=${{ github.run_id }}/runner=graviton3
    - runs-on=${{ github.run_id }}/runner=graviton4

    # RunsOn CI runners
    - runs-on=${{ github.run_id }}/runner=linux-x64-ci
    - runs-on=${{ github.run_id }}/runner=linux-arm64-ci

    # IBM GitHub Actions on Power/Z (ActionsPZ)
    - ubuntu-24.04-s390x
    - ubuntu-24.04-ppc64le
    - ubuntu-24.04-ppc64le-p10
