# .github/runs-on.yml
# RunsOn configuration for rscrypto benchmark and tuning lanes.

runners:
  # Intel Sapphire Rapids: primary Intel lane for high-end AVX-512 tuning/benching.
  intel-spr:
    cpu: 8
    ram: 16
    family: ["c7i", "m7i", "r7iz"]
    image: ubuntu24-full-x64
    spot: price-capacity-optimized
    retry: when-interrupted
    volume: 60gb:gp3:500mbs:4000iops
    ssh: true
    tags:
      - rscrypto:intel-spr
      - arch:x86-64
      - uarch:sapphire-rapids

  # Intel Ice Lake: stable lower-gen Intel lane for cross-generation signal.
  intel-icl:
    cpu: 8
    ram: 16
    family: ["c6i", "m6i", "r6i"]
    image: ubuntu24-full-x64
    spot: price-capacity-optimized
    retry: when-interrupted
    volume: 60gb:gp3:500mbs:4000iops
    ssh: true
    tags:
      - rscrypto:intel-icl
      - arch:x86-64
      - uarch:ice-lake

  # AMD Zen5 (Turin).
  amd-zen5:
    cpu: 8
    ram: 16
    family: ["m8a", "c8a", "r8a"]
    image: ubuntu24-full-x64
    spot: price-capacity-optimized
    retry: when-interrupted
    volume: 60gb:gp3:500mbs:4000iops
    ssh: true
    tags:
      - rscrypto:amd-zen5
      - arch:x86-64
      - uarch:zen5-turin

  # AMD Zen4 (Genoa).
  amd-zen4:
    cpu: 8
    ram: 16
    family: ["m7a", "c7a", "r7a"]
    image: ubuntu24-full-x64
    spot: price-capacity-optimized
    retry: when-interrupted
    volume: 60gb:gp3:500mbs:4000iops
    ssh: true
    tags:
      - rscrypto:amd-zen4
      - arch:x86-64
      - uarch:zen4-genoa

  # AWS Graviton3 explicit lane.
  graviton3:
    cpu: 8
    ram: 16
    family: ["c7g", "m7g", "r7g"]
    image: ubuntu24-full-arm64
    spot: price-capacity-optimized
    retry: when-interrupted
    volume: 60gb:gp3:500mbs:4000iops
    ssh: true
    tags:
      - rscrypto:graviton3
      - arch:aarch64
      - uarch:neoverse-v1

  # AWS Graviton4 explicit lane.
  graviton4:
    cpu: 8
    ram: 16
    family: ["c8g", "m8g", "r8g"]
    image: ubuntu24-full-arm64
    spot: price-capacity-optimized
    retry: when-interrupted
    volume: 60gb:gp3:500mbs:4000iops
    ssh: true
    tags:
      - rscrypto:graviton4
      - arch:aarch64
      - uarch:neoverse-v2

  # General CI runners (backup/overflow only).
  linux-x64-ci:
    cpu: [2, 4]
    ram: [4, 8]
    family: ["c7i", "m7i", "c7a", "m7a", "c6i", "m6i"]
    image: ubuntu24-full-x64
    spot: price-capacity-optimized
    volume: 50gb:gp3
    ssh: true
    extras: ["s3-cache"]
    tags:
      - rscrypto:ci
      - arch:x86-64

  linux-arm64-ci:
    cpu: [2, 4]
    ram: [4, 8]
    family: ["c7g", "m7g", "c8g", "m8g"]
    image: ubuntu24-full-arm64
    spot: price-capacity-optimized
    volume: 50gb:gp3
    ssh: true
    extras: ["s3-cache"]
    tags:
      - rscrypto:ci
      - arch:aarch64

admins:
  - mr.wolf
