name: Setup rscrypto Environment
description: |
  Install Rust toolchain, cargo tools, and configure caching.
  All actions (dtolnay/rust-toolchain, taiki-e/install-action) skip if already installed

inputs:
  cache-key:
    description: Additional cache key suffix
    required: false
    default: ""
  tools-mode:
    description: Tool installation mode (standard, ibm, minimal, none)
    required: false
    default: "standard"
  toolchain-components:
    description: Comma-separated list of toolchain components to install
    required: false
    default: "clippy, rustfmt, rust-src"

runs:
  using: composite
  steps:
    - name: Detect Host Architecture
      id: host
      shell: bash
      run: |
        echo "uname_m=$(uname -m)" >> "$GITHUB_OUTPUT"

    # Install Rust toolchain (reads version from rust-toolchain.toml)
    - name: Setup Toolchain
      uses: ./.github/actions/setup-toolchain
      with:
        components: ${{ inputs.toolchain-components }}

    # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    # Cache installed cargo tools separately (very stable, saves 30-90 seconds)
    # Tools rarely change, so this cache hits almost always
    # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    - name: Cache Cargo Tools
      if: inputs.tools-mode != 'none'
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684  # v4.2.3
      with:
        path: ~/.cargo/bin
        key: cargo-tools-${{ runner.os }}-${{ steps.host.outputs.uname_m }}-${{ inputs.tools-mode }}-v7
        # v7: bust stale cargo-rail cache entries from pre-v0.10 installs

    # Debug: show cache state before install
    - name: Debug Cache State
      if: inputs.tools-mode != 'none'
      shell: bash
      run: |
        echo "Cache key: cargo-tools-${{ runner.os }}-${{ steps.host.outputs.uname_m }}-${{ inputs.tools-mode }}-v7"
        echo "Tools in ~/.cargo/bin:"
        ls -la ~/.cargo/bin/ 2>/dev/null || echo "  (cache miss - directory empty or missing)"

    # Install all required cargo tools via cargo-binstall (parallel, pre-built binaries)
    # Skip if already in cache (install-tools.sh checks if tools exist)
    - name: Install Cargo Tools
      if: inputs.tools-mode != 'none'
      shell: bash
      env:
        CARGO_RAIL_VERSION: "0.10.12"
      run: scripts/ci/install-tools.sh ${{ inputs.tools-mode }}

    - name: Setup Rust Cache
      uses: Swatinem/rust-cache@779680da715d629ac1d338a641029a2f4372abb5  # v2.8.2
      with:
        # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
        # Cache Strategy:
        # - Caches: ~/.cargo (deps, tools) and ./target (build artifacts)
        # - Cache key includes: workflow, platform, rustc version, Cargo.lock hash
        # - Host triple automatically included in cache key
        # - Separate caches per workflow and target triple via 'key' input
        # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

        # Shared prefix: stable across commits (invalidates on bump)
        shared-key: "rscrypto-v1"

        # Workflow and platform-specific suffix
        key: ${{ inputs.cache-key }}

        # Cache even on test failures (build artifacts still useful)
        cache-on-failure: true

        # Save from main, and also from any workflow_dispatch runs.
        # The 'IBM' workflow check didn't work in reusable workflows; workflow_dispatch
        # is sufficient since IBM runners are only used via workflow_dispatch.
        save-if: ${{ github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch' }}
