codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: "70...95"
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: 80%

flags:
  tests:
    paths:
      - src/
    carryforward: true
  fuzz:
    paths:
      - src/
    carryforward: true

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: false

ignore:
  - "benches/"
  - "examples/"
  - "tests/"
  - "fuzz/"
  - "scripts/"
