name: Setup rscrypto Environment (Namespace)
description: |
  Install Rust toolchain, cargo tools, and configure Namespace caching.
  Optimized for Namespace-powered ARM64 runners with high-performance NVMe cache.

inputs:
  cache-key:
    description: Additional cache key suffix
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: Detect Host Architecture
      id: host
      shell: bash
      run: |
        echo "uname_m=$(uname -m)" >> "$GITHUB_OUTPUT"

    # Install Rust toolchain (reads version from rust-toolchain.toml)
    - name: Setup Toolchain
      uses: ./.github/actions/setup-toolchain
      with:
        components: clippy, rustfmt, rust-src

    # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    # Cache installed cargo tools separately (very stable, saves 30-90 seconds)
    # Using GitHub Actions cache (not Namespace) for portability
    # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    - name: Cache Cargo Tools
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684  # v4.2.3
      with:
        path: ~/.cargo/bin
        key: cargo-tools-${{ runner.os }}-${{ steps.host.outputs.uname_m }}-v5
        # v4: force refresh (cargo-audit install now uses `cargo install --force` when needed)

    # Install all required cargo tools via cargo-binstall (parallel, pre-built binaries)
    # Skip if already in cache (install-tools.sh checks if tools exist)
    - name: Install Cargo Tools
      shell: bash
      run: scripts/ci/install-tools.sh namespace

    - name: Setup Namespace Cache (Rust)
      uses: namespacelabs/nscloud-cache-action@446d8f390563cd54ca27e8de5bdb816f63c0b706  # v1.2.21
      with:
        # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
        # Namespace Caching Strategy:
        # - High-performance NVMe cache volumes (20GB+ minimum)
        # - Guaranteed locality: cache attached to same runner
        # - Zero impact on GitHub's 10GB cache quota
        # - Automatic Rust/Cargo support (target/, ~/.cargo)
        # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
        cache: rust
