#!/usr/bin/env bash
# shellcheck disable=SC2034
# Feature profile arrays are caller-visible outputs for sourced matrix scripts.

# This is the union of every profile historically owned by the compile and
# executable matrices. Execution may be narrowed, but compilation must not lose
# a declared feature contract.
COMPILE_FEATURE_SETS=(
  ""
  "alloc"
  "crc16"
  "crc24"
  "crc32"
  "crc64"
  "diag"
  "crc32,diag"
  "crc64,diag"
  "alloc,crc32"
  "sha2"
  "sha3"
  "websocket-sha1"
  "blake2b"
  "blake2s"
  "xxh3"
  "hmac"
  "hmac-sha3"
  "kmac"
  "hkdf"
  "pbkdf2"
  "poly1305"
  "rsa"
  "rsa,getrandom"
  "x25519"
  "chacha20poly1305"
  "aes-siv"
  "aegis256"
  "ascon-aead"
  "checksums"
  "alloc,checksums"
  "std,checksums"
  "std,checksums,diag"
  "hashes"
  "alloc,hashes"
  "std,hashes"
  "std,hashes,diag"
  "macs"
  "kdfs"
  "signatures"
  "key-exchange"
  "auth"
  "alloc,auth"
  "std,auth"
  "std,password-hashing,getrandom"
  "aead"
  "alloc,aead"
  "std,aead"
  "std,aead,diag"
  "std,checksums,hashes"
  "std,checksums,aead"
  "std,hashes,aead"
  "full"
  "std,full"
  "std,full,getrandom"
  "std,full,diag"
  "std,full,serde"
  "std,full,serde-secrets"
  "std,parallel"
  "std,full,portable-only"
)

# Execute the full primitive surface once for each behavior-changing boundary.
# Leaf and umbrella composition remains compile-checked above.
EXECUTABLE_FEATURE_SETS=(
  "websocket-sha1"
  "full"
  "std,full"
  "std,full,getrandom"
  "std,full,diag"
  "std,full,serde"
  "std,full,serde-secrets"
  "std,parallel"
  "std,full,portable-only"
)
