name: Setup Rust Toolchain (Dynamic)
description: |
  Install Rust toolchain reading version from rust-toolchain.toml.
  Single source of truth for toolchain version.

inputs:
  components:
    description: Comma-separated list of components to install
    required: false
    default: "clippy, rustfmt"

outputs:
  toolchain:
    description: The toolchain version that was installed
    value: ${{ steps.read-toolchain.outputs.toolchain }}

runs:
  using: composite
  steps:
    - name: Read Toolchain Version
      id: read-toolchain
      shell: bash
      run: |
        TOOLCHAIN=$(awk -F'"' '/^channel/ {print $2}' rust-toolchain.toml)
        echo "toolchain=$TOOLCHAIN" >> "$GITHUB_OUTPUT"
        echo "Using toolchain: $TOOLCHAIN"

    - name: Install Rust Toolchain (with components)
      if: inputs.components != ''
      uses: dtolnay/rust-toolchain@f7ccc83f9ed1e5b9c81d8a67d7ad1a747e22a561  # master
      with:
        toolchain: ${{ steps.read-toolchain.outputs.toolchain }}
        components: ${{ inputs.components }}

    - name: Install Rust Toolchain (no components)
      if: inputs.components == ''
      uses: dtolnay/rust-toolchain@f7ccc83f9ed1e5b9c81d8a67d7ad1a747e22a561  # master
      with:
        toolchain: ${{ steps.read-toolchain.outputs.toolchain }}
