//! AArch64 kernels for P-384 ECDH field arithmetic and comb selection.
//!
//! Each kernel computes the same canonical result as its portable authority
//! in `p384_portable.rs`: `montgomery_mul`, `montgomery_square`,
//! `Uint::add_mod`, `Uint::sub_mod`, the addition chains behind
//! `FieldElement::{triple, times4, times8}`, and the fixed-base comb scan. The field
//! kernels exist because LLVM lowers the portable 6x64 carry chains through
//! repeated flag materialization; here `MUL` and `UMULH` feed `ADDS`/`ADCS`
//! chains directly, since neither multiply instruction reads or writes NZCV.
//! On Apple cores the NZCV-writing and -reading instructions issue on fewer
//! ports than plain integer ones, so the kernels move work to the multiply
//! units and non-flag ALU instructions where the arithmetic allows.
//!
//! Multiplication and squaring form the full 768-bit product, reduce its low
//! half in place, and add the high half. With `-p^-1 mod 2^64 = 2^32 + 1`,
//! each reduction step replaces the low limb `t0` by `q = t0 + (t0 << 32)`
//! and uses `t + q * p = t - q * c + q * 2^384`, where `c = 2^384 - p =
//! 2^128 + 2^96 - 2^32 + 1`. The low limb of `q * c` equals `t0`, so it
//! cancels without a borrow; the next three limbs come from one `UMULH` by
//! `c0 = 2^64 - 2^32 + 1` and a `MUL`/`UMULH` pair by `c1 = 2^32 - 1`. The
//! register that held `t0` then holds `q` as the new top limb. A step's
//! borrow out of its fourth limb is kept in a register and subtracted at the
//! same position in the next step, where that limb has become the fourth
//! limb again; only the last step propagates its borrow through the window.
//!
//! The field kernels contain no branches, access no memory, and finish with a
//! `CSEL` or masked correction. The comb scan branches only on its public
//! loop counter and loads every table entry. Instruction timing is a target
//! property; this source shape is not a constant-time claim by itself.
//!
//! SECURITY: No block uses `options(pure)`. A pure block lets LLVM skip or
//! sink the kernel into a branch on the mask that later selects its result;
//! this made the signed-window negation branch on the digit sign.

/// Return `left * right * 2^-384 mod p` for canonical inputs below `p`.
///
/// Six row passes form the 768-bit schoolbook product. Each reduction step
/// keeps the low window below `2^384`, so after six steps it is at most `p`;
/// the high half of a product of canonical inputs is below `p`, so their sum
/// is below `2p` and one masked subtraction finishes the result.
#[inline(always)]
pub(super) fn montgomery_mul(left: [u64; 6], right: [u64; 6]) -> [u64; 6] {
  let [mut r0, mut r1, mut r2, mut r3, mut r4, mut r5] = right;
  // SAFETY: The block accesses no memory and uses no stack. It uses only base
  // A64 integer instructions, which every aarch64 target provides. Every
  // register it writes is a declared output, and NZCV is clobbered by default.
  unsafe {
    core::arch::asm!(
      "mul {w0}, {l0}, {b0}",
      "mul {w1}, {l0}, {b1}",
      "mul {w2}, {l0}, {b2}",
      "mul {w3}, {l0}, {b3}",
      "mul {w4}, {l0}, {b4}",
      "mul {w5}, {l0}, {b5}",
      "umulh {x}, {l0}, {b0}",
      "adds {w1}, {w1}, {x}",
      "umulh {x}, {l0}, {b1}",
      "adcs {w2}, {w2}, {x}",
      "umulh {x}, {l0}, {b2}",
      "adcs {w3}, {w3}, {x}",
      "umulh {x}, {l0}, {b3}",
      "adcs {w4}, {w4}, {x}",
      "umulh {x}, {l0}, {b4}",
      "adcs {w5}, {w5}, {x}",
      "umulh {x}, {l0}, {b5}",
      "adc {w6}, {x}, xzr",
      "mul {x}, {l1}, {b0}",
      "adds {w1}, {w1}, {x}",
      "mul {x}, {l1}, {b1}",
      "adcs {w2}, {w2}, {x}",
      "mul {x}, {l1}, {b2}",
      "adcs {w3}, {w3}, {x}",
      "mul {x}, {l1}, {b3}",
      "adcs {w4}, {w4}, {x}",
      "mul {x}, {l1}, {b4}",
      "adcs {w5}, {w5}, {x}",
      "mul {x}, {l1}, {b5}",
      "adcs {w6}, {w6}, {x}",
      "adc {w7}, xzr, xzr",
      "umulh {x}, {l1}, {b0}",
      "adds {w2}, {w2}, {x}",
      "umulh {x}, {l1}, {b1}",
      "adcs {w3}, {w3}, {x}",
      "umulh {x}, {l1}, {b2}",
      "adcs {w4}, {w4}, {x}",
      "umulh {x}, {l1}, {b3}",
      "adcs {w5}, {w5}, {x}",
      "umulh {x}, {l1}, {b4}",
      "adcs {w6}, {w6}, {x}",
      "umulh {x}, {l1}, {b5}",
      "adc {w7}, {w7}, {x}",
      "mul {x}, {l2}, {b0}",
      "adds {w2}, {w2}, {x}",
      "mul {x}, {l2}, {b1}",
      "adcs {w3}, {w3}, {x}",
      "mul {x}, {l2}, {b2}",
      "adcs {w4}, {w4}, {x}",
      "mul {x}, {l2}, {b3}",
      "adcs {w5}, {w5}, {x}",
      "mul {x}, {l2}, {b4}",
      "adcs {w6}, {w6}, {x}",
      "mul {x}, {l2}, {b5}",
      "adcs {w7}, {w7}, {x}",
      "adc {w8}, xzr, xzr",
      "umulh {x}, {l2}, {b0}",
      "adds {w3}, {w3}, {x}",
      "umulh {x}, {l2}, {b1}",
      "adcs {w4}, {w4}, {x}",
      "umulh {x}, {l2}, {b2}",
      "adcs {w5}, {w5}, {x}",
      "umulh {x}, {l2}, {b3}",
      "adcs {w6}, {w6}, {x}",
      "umulh {x}, {l2}, {b4}",
      "adcs {w7}, {w7}, {x}",
      "umulh {x}, {l2}, {b5}",
      "adc {w8}, {w8}, {x}",
      "mul {x}, {l3}, {b0}",
      "adds {w3}, {w3}, {x}",
      "mul {x}, {l3}, {b1}",
      "adcs {w4}, {w4}, {x}",
      "mul {x}, {l3}, {b2}",
      "adcs {w5}, {w5}, {x}",
      "mul {x}, {l3}, {b3}",
      "adcs {w6}, {w6}, {x}",
      "mul {x}, {l3}, {b4}",
      "adcs {w7}, {w7}, {x}",
      "mul {x}, {l3}, {b5}",
      "adcs {w8}, {w8}, {x}",
      "adc {w9}, xzr, xzr",
      "umulh {x}, {l3}, {b0}",
      "adds {w4}, {w4}, {x}",
      "umulh {x}, {l3}, {b1}",
      "adcs {w5}, {w5}, {x}",
      "umulh {x}, {l3}, {b2}",
      "adcs {w6}, {w6}, {x}",
      "umulh {x}, {l3}, {b3}",
      "adcs {w7}, {w7}, {x}",
      "umulh {x}, {l3}, {b4}",
      "adcs {w8}, {w8}, {x}",
      "umulh {x}, {l3}, {b5}",
      "adc {w9}, {w9}, {x}",
      "mul {x}, {l4}, {b0}",
      "adds {w4}, {w4}, {x}",
      "mul {x}, {l4}, {b1}",
      "adcs {w5}, {w5}, {x}",
      "mul {x}, {l4}, {b2}",
      "adcs {w6}, {w6}, {x}",
      "mul {x}, {l4}, {b3}",
      "adcs {w7}, {w7}, {x}",
      "mul {x}, {l4}, {b4}",
      "adcs {w8}, {w8}, {x}",
      "mul {x}, {l4}, {b5}",
      "adcs {w9}, {w9}, {x}",
      "adc {w10}, xzr, xzr",
      "umulh {x}, {l4}, {b0}",
      "adds {w5}, {w5}, {x}",
      "umulh {x}, {l4}, {b1}",
      "adcs {w6}, {w6}, {x}",
      "umulh {x}, {l4}, {b2}",
      "adcs {w7}, {w7}, {x}",
      "umulh {x}, {l4}, {b3}",
      "adcs {w8}, {w8}, {x}",
      "umulh {x}, {l4}, {b4}",
      "adcs {w9}, {w9}, {x}",
      "umulh {x}, {l4}, {b5}",
      "adc {w10}, {w10}, {x}",
      "mul {x}, {l5}, {b0}",
      "adds {w5}, {w5}, {x}",
      "mul {x}, {l5}, {b1}",
      "adcs {w6}, {w6}, {x}",
      "mul {x}, {l5}, {b2}",
      "adcs {w7}, {w7}, {x}",
      "mul {x}, {l5}, {b3}",
      "adcs {w8}, {w8}, {x}",
      "mul {x}, {l5}, {b4}",
      "adcs {w9}, {w9}, {x}",
      "mul {x}, {l5}, {b5}",
      "adcs {w10}, {w10}, {x}",
      "adc {w11}, xzr, xzr",
      "umulh {x}, {l5}, {b0}",
      "adds {w6}, {w6}, {x}",
      "umulh {x}, {l5}, {b1}",
      "adcs {w7}, {w7}, {x}",
      "umulh {x}, {l5}, {b2}",
      "adcs {w8}, {w8}, {x}",
      "umulh {x}, {l5}, {b3}",
      "adcs {w9}, {w9}, {x}",
      "umulh {x}, {l5}, {b4}",
      "adcs {w10}, {w10}, {x}",
      "umulh {x}, {l5}, {b5}",
      "adc {w11}, {w11}, {x}",
      "mov {b5:w}, #-1",
      "neg {b4}, {b5}",
      "add {w0}, {w0}, {w0}, lsl #32",
      "umulh {b3}, {w0}, {b4}",
      "mul {b1}, {w0}, {b5}",
      "umulh {b2}, {w0}, {b5}",
      "adds {b1}, {b1}, {b3}",
      "adcs {b2}, {b2}, {w0}",
      "cset {b3}, hs",
      "subs {w1}, {w1}, {b1}",
      "sbcs {w2}, {w2}, {b2}",
      "sbcs {w3}, {w3}, {b3}",
      "cset {b0}, lo",
      "add {w1}, {w1}, {w1}, lsl #32",
      "umulh {b3}, {w1}, {b4}",
      "mul {b1}, {w1}, {b5}",
      "umulh {b2}, {w1}, {b5}",
      "adds {b1}, {b1}, {b3}",
      "adcs {b2}, {b2}, {w1}",
      "adc {b3}, {b0}, xzr",
      "subs {w2}, {w2}, {b1}",
      "sbcs {w3}, {w3}, {b2}",
      "sbcs {w4}, {w4}, {b3}",
      "cset {b0}, lo",
      "add {w2}, {w2}, {w2}, lsl #32",
      "umulh {b3}, {w2}, {b4}",
      "mul {b1}, {w2}, {b5}",
      "umulh {b2}, {w2}, {b5}",
      "adds {b1}, {b1}, {b3}",
      "adcs {b2}, {b2}, {w2}",
      "adc {b3}, {b0}, xzr",
      "subs {w3}, {w3}, {b1}",
      "sbcs {w4}, {w4}, {b2}",
      "sbcs {w5}, {w5}, {b3}",
      "cset {b0}, lo",
      "add {w3}, {w3}, {w3}, lsl #32",
      "umulh {b3}, {w3}, {b4}",
      "mul {b1}, {w3}, {b5}",
      "umulh {b2}, {w3}, {b5}",
      "adds {b1}, {b1}, {b3}",
      "adcs {b2}, {b2}, {w3}",
      "adc {b3}, {b0}, xzr",
      "subs {w4}, {w4}, {b1}",
      "sbcs {w5}, {w5}, {b2}",
      "sbcs {w0}, {w0}, {b3}",
      "cset {b0}, lo",
      "add {w4}, {w4}, {w4}, lsl #32",
      "umulh {b3}, {w4}, {b4}",
      "mul {b1}, {w4}, {b5}",
      "umulh {b2}, {w4}, {b5}",
      "adds {b1}, {b1}, {b3}",
      "adcs {b2}, {b2}, {w4}",
      "adc {b3}, {b0}, xzr",
      "subs {w5}, {w5}, {b1}",
      "sbcs {w0}, {w0}, {b2}",
      "sbcs {w1}, {w1}, {b3}",
      "cset {b0}, lo",
      "add {w5}, {w5}, {w5}, lsl #32",
      "umulh {b3}, {w5}, {b4}",
      "mul {b1}, {w5}, {b5}",
      "umulh {b2}, {w5}, {b5}",
      "adds {b1}, {b1}, {b3}",
      "adcs {b2}, {b2}, {w5}",
      "adc {b3}, {b0}, xzr",
      "subs {w0}, {w0}, {b1}",
      "sbcs {w1}, {w1}, {b2}",
      "sbcs {w2}, {w2}, {b3}",
      "sbcs {w3}, {w3}, xzr",
      "sbcs {w4}, {w4}, xzr",
      "sbc {w5}, {w5}, xzr",
      "adds {w0}, {w0}, {w6}",
      "adcs {w1}, {w1}, {w7}",
      "adcs {w2}, {w2}, {w8}",
      "adcs {w3}, {w3}, {w9}",
      "adcs {w4}, {w4}, {w10}",
      "adcs {w5}, {w5}, {w11}",
      "cset {x}, hs",
      "adds {w6}, {w0}, {b4}",
      "adcs {w7}, {w1}, {b5}",
      "mov {b0}, #1",
      "adcs {w8}, {w2}, {b0}",
      "adcs {w9}, {w3}, xzr",
      "adcs {w10}, {w4}, xzr",
      "adcs {w11}, {w5}, xzr",
      "adc {x}, {x}, xzr",
      "cmp {x}, #0",
      "csel {b0}, {w6}, {w0}, ne",
      "csel {b1}, {w7}, {w1}, ne",
      "csel {b2}, {w8}, {w2}, ne",
      "csel {b3}, {w9}, {w3}, ne",
      "csel {b4}, {w10}, {w4}, ne",
      "csel {b5}, {w11}, {w5}, ne",
      l0 = in(reg) left[0],
      l1 = in(reg) left[1],
      l2 = in(reg) left[2],
      l3 = in(reg) left[3],
      l4 = in(reg) left[4],
      l5 = in(reg) left[5],
      b0 = inout(reg) r0,
      b1 = inout(reg) r1,
      b2 = inout(reg) r2,
      b3 = inout(reg) r3,
      b4 = inout(reg) r4,
      b5 = inout(reg) r5,
      x = out(reg) _,
      w0 = out(reg) _,
      w1 = out(reg) _,
      w2 = out(reg) _,
      w3 = out(reg) _,
      w4 = out(reg) _,
      w5 = out(reg) _,
      w6 = out(reg) _,
      w7 = out(reg) _,
      w8 = out(reg) _,
      w9 = out(reg) _,
      w10 = out(reg) _,
      w11 = out(reg) _,
      options(nomem, nostack),
    );
  }
  [r0, r1, r2, r3, r4, r5]
}

/// Return `value^2 * 2^-384 mod p` for a canonical input below `p`.
///
/// The kernel forms the 768-bit square from 15 doubled cross products and six
/// diagonal products, then reduces it as `montgomery_mul` does. The input
/// registers are dead after the diagonal products and hold the reduction
/// quotient, its partial products, and the constants `c0` and `c1`.
#[inline(always)]
pub(super) fn montgomery_square(value: [u64; 6]) -> [u64; 6] {
  let [mut r0, mut r1, mut r2, mut r3, mut r4, mut r5] = value;
  // SAFETY: The block accesses no memory and uses no stack. It uses only base
  // A64 integer instructions, which every aarch64 target provides. Every
  // register it writes is a declared output, and NZCV is clobbered by default.
  unsafe {
    core::arch::asm!(
      "mul {w1}, {a0}, {a1}",
      "mul {w2}, {a0}, {a2}",
      "mul {w3}, {a0}, {a3}",
      "mul {w4}, {a0}, {a4}",
      "mul {w5}, {a0}, {a5}",
      "umulh {x}, {a0}, {a1}",
      "adds {w2}, {w2}, {x}",
      "umulh {x}, {a0}, {a2}",
      "adcs {w3}, {w3}, {x}",
      "umulh {x}, {a0}, {a3}",
      "adcs {w4}, {w4}, {x}",
      "umulh {x}, {a0}, {a4}",
      "adcs {w5}, {w5}, {x}",
      "umulh {x}, {a0}, {a5}",
      "adc {w6}, {x}, xzr",
      "mul {x}, {a1}, {a2}",
      "adds {w3}, {w3}, {x}",
      "mul {x}, {a1}, {a3}",
      "adcs {w4}, {w4}, {x}",
      "mul {x}, {a1}, {a4}",
      "adcs {w5}, {w5}, {x}",
      "mul {x}, {a1}, {a5}",
      "adcs {w6}, {w6}, {x}",
      "adc {w7}, xzr, xzr",
      "umulh {x}, {a1}, {a2}",
      "adds {w4}, {w4}, {x}",
      "umulh {x}, {a1}, {a3}",
      "adcs {w5}, {w5}, {x}",
      "umulh {x}, {a1}, {a4}",
      "adcs {w6}, {w6}, {x}",
      "umulh {x}, {a1}, {a5}",
      "adc {w7}, {w7}, {x}",
      "mul {x}, {a2}, {a3}",
      "adds {w5}, {w5}, {x}",
      "mul {x}, {a2}, {a4}",
      "adcs {w6}, {w6}, {x}",
      "mul {x}, {a2}, {a5}",
      "adcs {w7}, {w7}, {x}",
      "adc {w8}, xzr, xzr",
      "umulh {x}, {a2}, {a3}",
      "adds {w6}, {w6}, {x}",
      "umulh {x}, {a2}, {a4}",
      "adcs {w7}, {w7}, {x}",
      "umulh {x}, {a2}, {a5}",
      "adc {w8}, {w8}, {x}",
      "mul {x}, {a3}, {a4}",
      "adds {w7}, {w7}, {x}",
      "mul {x}, {a3}, {a5}",
      "adcs {w8}, {w8}, {x}",
      "adc {w9}, xzr, xzr",
      "umulh {x}, {a3}, {a4}",
      "adds {w8}, {w8}, {x}",
      "umulh {x}, {a3}, {a5}",
      "adc {w9}, {w9}, {x}",
      "mul {x}, {a4}, {a5}",
      "adds {w9}, {w9}, {x}",
      "adc {w10}, xzr, xzr",
      "umulh {x}, {a4}, {a5}",
      "add {w10}, {w10}, {x}",
      "adds {w1}, {w1}, {w1}",
      "adcs {w2}, {w2}, {w2}",
      "adcs {w3}, {w3}, {w3}",
      "adcs {w4}, {w4}, {w4}",
      "adcs {w5}, {w5}, {w5}",
      "adcs {w6}, {w6}, {w6}",
      "adcs {w7}, {w7}, {w7}",
      "adcs {w8}, {w8}, {w8}",
      "adcs {w9}, {w9}, {w9}",
      "adcs {w10}, {w10}, {w10}",
      "adc {w11}, xzr, xzr",
      "mul {w0}, {a0}, {a0}",
      "umulh {x}, {a0}, {a0}",
      "adds {w1}, {w1}, {x}",
      "mul {x}, {a1}, {a1}",
      "adcs {w2}, {w2}, {x}",
      "umulh {x}, {a1}, {a1}",
      "adcs {w3}, {w3}, {x}",
      "mul {x}, {a2}, {a2}",
      "adcs {w4}, {w4}, {x}",
      "umulh {x}, {a2}, {a2}",
      "adcs {w5}, {w5}, {x}",
      "mul {x}, {a3}, {a3}",
      "adcs {w6}, {w6}, {x}",
      "umulh {x}, {a3}, {a3}",
      "adcs {w7}, {w7}, {x}",
      "mul {x}, {a4}, {a4}",
      "adcs {w8}, {w8}, {x}",
      "umulh {x}, {a4}, {a4}",
      "adcs {w9}, {w9}, {x}",
      "mul {x}, {a5}, {a5}",
      "adcs {w10}, {w10}, {x}",
      "umulh {x}, {a5}, {a5}",
      "adc {w11}, {w11}, {x}",
      "mov {a5:w}, #-1",
      "neg {a4}, {a5}",
      "add {w0}, {w0}, {w0}, lsl #32",
      "umulh {a3}, {w0}, {a4}",
      "mul {a1}, {w0}, {a5}",
      "umulh {a2}, {w0}, {a5}",
      "adds {a1}, {a1}, {a3}",
      "adcs {a2}, {a2}, {w0}",
      "cset {a3}, hs",
      "subs {w1}, {w1}, {a1}",
      "sbcs {w2}, {w2}, {a2}",
      "sbcs {w3}, {w3}, {a3}",
      "cset {a0}, lo",
      "add {w1}, {w1}, {w1}, lsl #32",
      "umulh {a3}, {w1}, {a4}",
      "mul {a1}, {w1}, {a5}",
      "umulh {a2}, {w1}, {a5}",
      "adds {a1}, {a1}, {a3}",
      "adcs {a2}, {a2}, {w1}",
      "adc {a3}, {a0}, xzr",
      "subs {w2}, {w2}, {a1}",
      "sbcs {w3}, {w3}, {a2}",
      "sbcs {w4}, {w4}, {a3}",
      "cset {a0}, lo",
      "add {w2}, {w2}, {w2}, lsl #32",
      "umulh {a3}, {w2}, {a4}",
      "mul {a1}, {w2}, {a5}",
      "umulh {a2}, {w2}, {a5}",
      "adds {a1}, {a1}, {a3}",
      "adcs {a2}, {a2}, {w2}",
      "adc {a3}, {a0}, xzr",
      "subs {w3}, {w3}, {a1}",
      "sbcs {w4}, {w4}, {a2}",
      "sbcs {w5}, {w5}, {a3}",
      "cset {a0}, lo",
      "add {w3}, {w3}, {w3}, lsl #32",
      "umulh {a3}, {w3}, {a4}",
      "mul {a1}, {w3}, {a5}",
      "umulh {a2}, {w3}, {a5}",
      "adds {a1}, {a1}, {a3}",
      "adcs {a2}, {a2}, {w3}",
      "adc {a3}, {a0}, xzr",
      "subs {w4}, {w4}, {a1}",
      "sbcs {w5}, {w5}, {a2}",
      "sbcs {w0}, {w0}, {a3}",
      "cset {a0}, lo",
      "add {w4}, {w4}, {w4}, lsl #32",
      "umulh {a3}, {w4}, {a4}",
      "mul {a1}, {w4}, {a5}",
      "umulh {a2}, {w4}, {a5}",
      "adds {a1}, {a1}, {a3}",
      "adcs {a2}, {a2}, {w4}",
      "adc {a3}, {a0}, xzr",
      "subs {w5}, {w5}, {a1}",
      "sbcs {w0}, {w0}, {a2}",
      "sbcs {w1}, {w1}, {a3}",
      "cset {a0}, lo",
      "add {w5}, {w5}, {w5}, lsl #32",
      "umulh {a3}, {w5}, {a4}",
      "mul {a1}, {w5}, {a5}",
      "umulh {a2}, {w5}, {a5}",
      "adds {a1}, {a1}, {a3}",
      "adcs {a2}, {a2}, {w5}",
      "adc {a3}, {a0}, xzr",
      "subs {w0}, {w0}, {a1}",
      "sbcs {w1}, {w1}, {a2}",
      "sbcs {w2}, {w2}, {a3}",
      "sbcs {w3}, {w3}, xzr",
      "sbcs {w4}, {w4}, xzr",
      "sbc {w5}, {w5}, xzr",
      "adds {w0}, {w0}, {w6}",
      "adcs {w1}, {w1}, {w7}",
      "adcs {w2}, {w2}, {w8}",
      "adcs {w3}, {w3}, {w9}",
      "adcs {w4}, {w4}, {w10}",
      "adcs {w5}, {w5}, {w11}",
      "cset {x}, hs",
      "adds {w6}, {w0}, {a4}",
      "adcs {w7}, {w1}, {a5}",
      "mov {a0}, #1",
      "adcs {w8}, {w2}, {a0}",
      "adcs {w9}, {w3}, xzr",
      "adcs {w10}, {w4}, xzr",
      "adcs {w11}, {w5}, xzr",
      "adc {x}, {x}, xzr",
      "cmp {x}, #0",
      "csel {a0}, {w6}, {w0}, ne",
      "csel {a1}, {w7}, {w1}, ne",
      "csel {a2}, {w8}, {w2}, ne",
      "csel {a3}, {w9}, {w3}, ne",
      "csel {a4}, {w10}, {w4}, ne",
      "csel {a5}, {w11}, {w5}, ne",
      a0 = inout(reg) r0,
      a1 = inout(reg) r1,
      a2 = inout(reg) r2,
      a3 = inout(reg) r3,
      a4 = inout(reg) r4,
      a5 = inout(reg) r5,
      x = out(reg) _,
      w0 = out(reg) _,
      w1 = out(reg) _,
      w2 = out(reg) _,
      w3 = out(reg) _,
      w4 = out(reg) _,
      w5 = out(reg) _,
      w6 = out(reg) _,
      w7 = out(reg) _,
      w8 = out(reg) _,
      w9 = out(reg) _,
      w10 = out(reg) _,
      w11 = out(reg) _,
      options(nomem, nostack),
    );
  }
  [r0, r1, r2, r3, r4, r5]
}

/// Return `left + right mod p` for canonical inputs below `p`.
///
/// The sum is below `2p`. Adding `2^384 - p` carries out of 385 bits exactly
/// when the sum is at least `p`, and `CSEL` then keeps the low 384 bits.
#[inline(always)]
pub(super) fn add_mod(left: [u64; 6], right: [u64; 6]) -> [u64; 6] {
  let [mut r0, mut r1, mut r2, mut r3, mut r4, mut r5] = left;
  // SAFETY: The block accesses no memory and uses no stack. It uses only base
  // A64 integer instructions, which every aarch64 target provides. Every
  // register it writes is a declared output, and NZCV is clobbered by default.
  unsafe {
    core::arch::asm!(
      "adds {s0}, {s0}, {b0}",
      "adcs {s1}, {s1}, {b1}",
      "adcs {s2}, {s2}, {b2}",
      "adcs {s3}, {s3}, {b3}",
      "adcs {s4}, {s4}, {b4}",
      "adcs {s5}, {s5}, {b5}",
      "adc {c}, xzr, xzr",
      // 2^384 - p = [2^64 - 2^32 + 1, 2^32 - 1, 1, 0, 0, 0].
      "mov {k1:w}, #-1",
      "neg {k0}, {k1}",
      "adds {b0}, {s0}, {k0}",
      "adcs {b1}, {s1}, {k1}",
      "mov {k1}, #1",
      "adcs {b2}, {s2}, {k1}",
      "adcs {b3}, {s3}, xzr",
      "adcs {b4}, {s4}, xzr",
      "adcs {b5}, {s5}, xzr",
      "adc {c}, {c}, xzr",
      "cmp {c}, #0",
      "csel {s0}, {b0}, {s0}, ne",
      "csel {s1}, {b1}, {s1}, ne",
      "csel {s2}, {b2}, {s2}, ne",
      "csel {s3}, {b3}, {s3}, ne",
      "csel {s4}, {b4}, {s4}, ne",
      "csel {s5}, {b5}, {s5}, ne",
      s0 = inout(reg) r0,
      s1 = inout(reg) r1,
      s2 = inout(reg) r2,
      s3 = inout(reg) r3,
      s4 = inout(reg) r4,
      s5 = inout(reg) r5,
      b0 = inout(reg) right[0] => _,
      b1 = inout(reg) right[1] => _,
      b2 = inout(reg) right[2] => _,
      b3 = inout(reg) right[3] => _,
      b4 = inout(reg) right[4] => _,
      b5 = inout(reg) right[5] => _,
      c = out(reg) _,
      k0 = out(reg) _,
      k1 = out(reg) _,
      options(nomem, nostack),
    );
  }
  [r0, r1, r2, r3, r4, r5]
}

/// Return `value * k mod p` for a canonical input below `p` and `k <= 8`.
///
/// The six-limb product leaves a top limb below `k`. Folding it through
/// `top * 2^384 = top * c (mod p)` uses the multiply units and gives a value
/// below `2^384 + 8c`, which is below `2p`; one masked subtraction finishes.
#[inline(always)]
pub(super) fn mul_small(value: [u64; 6], k: u64) -> [u64; 6] {
  debug_assert!(k <= 8);
  let [mut r0, mut r1, mut r2, mut r3, mut r4, mut r5] = value;
  // SAFETY: The block accesses no memory and uses no stack. It uses only base
  // A64 integer instructions, which every aarch64 target provides. Every
  // register it writes is a declared output, and NZCV is clobbered by default.
  unsafe {
    core::arch::asm!(
      "mul {t0}, {a0}, {k}",
      "umulh {h}, {a0}, {k}",
      "mul {t1}, {a1}, {k}",
      "adds {t1}, {t1}, {h}",
      "umulh {h}, {a1}, {k}",
      "mul {t2}, {a2}, {k}",
      "adcs {t2}, {t2}, {h}",
      "umulh {h}, {a2}, {k}",
      "mul {t3}, {a3}, {k}",
      "adcs {t3}, {t3}, {h}",
      "umulh {h}, {a3}, {k}",
      "mul {t4}, {a4}, {k}",
      "adcs {t4}, {t4}, {h}",
      "umulh {h}, {a4}, {k}",
      "mul {t5}, {a5}, {k}",
      "adcs {t5}, {t5}, {h}",
      "umulh {h}, {a5}, {k}",
      "adc {top}, {h}, xzr",
      "mov {c1:w}, #-1",
      "neg {c0}, {c1}",
      "mul {h}, {top}, {c0}",
      "umulh {cv}, {top}, {c0}",
      "mul {m1}, {top}, {c1}",
      "add {m1}, {m1}, {cv}",
      "adds {t0}, {t0}, {h}",
      "adcs {t1}, {t1}, {m1}",
      "adcs {t2}, {t2}, {top}",
      "adcs {t3}, {t3}, xzr",
      "adcs {t4}, {t4}, xzr",
      "adcs {t5}, {t5}, xzr",
      "cset {cv}, hs",
      "adds {a0}, {t0}, {c0}",
      "adcs {a1}, {t1}, {c1}",
      "mov {h}, #1",
      "adcs {a2}, {t2}, {h}",
      "adcs {a3}, {t3}, xzr",
      "adcs {a4}, {t4}, xzr",
      "adcs {a5}, {t5}, xzr",
      "adc {cv}, {cv}, xzr",
      "cmp {cv}, #0",
      "csel {a0}, {a0}, {t0}, ne",
      "csel {a1}, {a1}, {t1}, ne",
      "csel {a2}, {a2}, {t2}, ne",
      "csel {a3}, {a3}, {t3}, ne",
      "csel {a4}, {a4}, {t4}, ne",
      "csel {a5}, {a5}, {t5}, ne",
      a0 = inout(reg) r0,
      a1 = inout(reg) r1,
      a2 = inout(reg) r2,
      a3 = inout(reg) r3,
      a4 = inout(reg) r4,
      a5 = inout(reg) r5,
      k = in(reg) k,
      t0 = out(reg) _,
      t1 = out(reg) _,
      t2 = out(reg) _,
      t3 = out(reg) _,
      t4 = out(reg) _,
      t5 = out(reg) _,
      h = out(reg) _,
      top = out(reg) _,
      m1 = out(reg) _,
      c0 = out(reg) _,
      c1 = out(reg) _,
      cv = out(reg) _,
      options(nomem, nostack),
    );
  }
  [r0, r1, r2, r3, r4, r5]
}

/// Return `left - right mod p` for canonical inputs below `p`.
///
/// A borrow out of the subtraction becomes an all-ones mask that selects `p`
/// for the correcting addition, whose final carry is discarded.
#[inline(always)]
pub(super) fn sub_mod(left: [u64; 6], right: [u64; 6]) -> [u64; 6] {
  let [mut r0, mut r1, mut r2, mut r3, mut r4, mut r5] = left;
  // SAFETY: The block accesses no memory and uses no stack. It uses only base
  // A64 integer instructions, which every aarch64 target provides. Every
  // register it writes is a declared output, and NZCV is clobbered by default.
  unsafe {
    core::arch::asm!(
      "subs {d0}, {d0}, {b0}",
      "sbcs {d1}, {d1}, {b1}",
      "sbcs {d2}, {d2}, {b2}",
      "sbcs {d3}, {d3}, {b3}",
      "sbcs {d4}, {d4}, {b4}",
      "sbcs {d5}, {d5}, {b5}",
      "sbc {m}, xzr, xzr",
      "and {p0}, {m}, #0x00000000ffffffff",
      "and {p1}, {m}, #0xffffffff00000000",
      "and {p2}, {m}, #0xfffffffffffffffe",
      "adds {d0}, {d0}, {p0}",
      "adcs {d1}, {d1}, {p1}",
      "adcs {d2}, {d2}, {p2}",
      "adcs {d3}, {d3}, {m}",
      "adcs {d4}, {d4}, {m}",
      "adc {d5}, {d5}, {m}",
      d0 = inout(reg) r0,
      d1 = inout(reg) r1,
      d2 = inout(reg) r2,
      d3 = inout(reg) r3,
      d4 = inout(reg) r4,
      d5 = inout(reg) r5,
      b0 = in(reg) right[0],
      b1 = in(reg) right[1],
      b2 = in(reg) right[2],
      b3 = in(reg) right[3],
      b4 = in(reg) right[4],
      b5 = in(reg) right[5],
      m = out(reg) _,
      p0 = out(reg) _,
      p1 = out(reg) _,
      p2 = out(reg) _,
      options(nomem, nostack),
    );
  }
  [r0, r1, r2, r3, r4, r5]
}

const COMB_TABLE_ENTRIES: usize = 256;
// The table entries are single-field wrappers around `[u64; 6]`. A 48-byte
// wrapper leaves no room for padding, so each entry is exactly its limbs and
// the array stride is 48 bytes.
const _: () = assert!(core::mem::size_of::<CombEntry>() == 48);
const _: () = assert!(core::mem::align_of::<CombEntry>() == core::mem::align_of::<u64>());

type CombEntry = super::super::ecdsa_generator_tables::Uint<6>;

/// Return the `x` and `y` limbs of `table_x[digit]` and `table_y[digit]`.
///
/// Every entry of both tables is loaded in index order. A vector lane counter
/// is compared with the digit through `CMEQ`, and `BIT` inserts the entry
/// under that mask, so neither control flow nor load addresses depend on
/// `digit`. A digit outside the table selects all-zero limbs.
#[inline(always)]
pub(super) fn select_comb(
  table_x: &[CombEntry; COMB_TABLE_ENTRIES],
  table_y: &[CombEntry; COMB_TABLE_ENTRIES],
  digit: usize,
) -> ([u64; 6], [u64; 6]) {
  let (x0, x1, x2, x3, x4, x5): (u64, u64, u64, u64, u64, u64);
  let (y0, y1, y2, y3, y4, y5): (u64, u64, u64, u64, u64, u64);
  // SAFETY: Each table is a live shared reference to 256 contiguous 48-byte
  // entries, checked by the layout assertions above. The loop runs exactly
  // 256 times and each pointer advances 48 bytes per iteration through three
  // 16-byte `LD1` loads, so it reads bytes 0..12288 of its table and nothing
  // else. `LD1` with `.2d` needs only 8-byte alignment and loads each `u64`
  // lane with the target byte order. The block writes no memory and uses no
  // stack. It uses only base A64 and Advanced SIMD instructions, which every
  // aarch64 Rust target enables. Every register it writes is a declared
  // output, and NZCV is clobbered by default.
  unsafe {
    core::arch::asm!(
      "dup {wanted:v}.2d, {digit}",
      "movi {index:v}.2d, #0",
      "mov {count}, #1",
      "dup {one:v}.2d, {count}",
      "mov {count}, #256",
      "movi {ax0:v}.2d, #0",
      "movi {ax1:v}.2d, #0",
      "movi {ax2:v}.2d, #0",
      "movi {ay0:v}.2d, #0",
      "movi {ay1:v}.2d, #0",
      "movi {ay2:v}.2d, #0",
      "2:",
      "cmeq {mask:v}.2d, {index:v}.2d, {wanted:v}.2d",
      "ld1 {{{ex0:v}.2d}}, [{px}], #16",
      "ld1 {{{ex1:v}.2d}}, [{px}], #16",
      "ld1 {{{ex2:v}.2d}}, [{px}], #16",
      "ld1 {{{ey0:v}.2d}}, [{py}], #16",
      "ld1 {{{ey1:v}.2d}}, [{py}], #16",
      "ld1 {{{ey2:v}.2d}}, [{py}], #16",
      "bit {ax0:v}.16b, {ex0:v}.16b, {mask:v}.16b",
      "bit {ax1:v}.16b, {ex1:v}.16b, {mask:v}.16b",
      "bit {ax2:v}.16b, {ex2:v}.16b, {mask:v}.16b",
      "bit {ay0:v}.16b, {ey0:v}.16b, {mask:v}.16b",
      "bit {ay1:v}.16b, {ey1:v}.16b, {mask:v}.16b",
      "bit {ay2:v}.16b, {ey2:v}.16b, {mask:v}.16b",
      "add {index:v}.2d, {index:v}.2d, {one:v}.2d",
      "subs {count}, {count}, #1",
      "b.ne 2b",
      "mov {x0}, {ax0:v}.d[0]",
      "mov {x1}, {ax0:v}.d[1]",
      "mov {x2}, {ax1:v}.d[0]",
      "mov {x3}, {ax1:v}.d[1]",
      "mov {x4}, {ax2:v}.d[0]",
      "mov {x5}, {ax2:v}.d[1]",
      "mov {y0}, {ay0:v}.d[0]",
      "mov {y1}, {ay0:v}.d[1]",
      "mov {y2}, {ay1:v}.d[0]",
      "mov {y3}, {ay1:v}.d[1]",
      "mov {y4}, {ay2:v}.d[0]",
      "mov {y5}, {ay2:v}.d[1]",
      digit = in(reg) digit,
      px = inout(reg) table_x.as_ptr() => _,
      py = inout(reg) table_y.as_ptr() => _,
      count = out(reg) _,
      x0 = lateout(reg) x0,
      x1 = lateout(reg) x1,
      x2 = lateout(reg) x2,
      x3 = lateout(reg) x3,
      x4 = lateout(reg) x4,
      x5 = lateout(reg) x5,
      y0 = lateout(reg) y0,
      y1 = lateout(reg) y1,
      y2 = lateout(reg) y2,
      y3 = lateout(reg) y3,
      y4 = lateout(reg) y4,
      y5 = lateout(reg) y5,
      wanted = out(vreg) _,
      index = out(vreg) _,
      one = out(vreg) _,
      mask = out(vreg) _,
      ex0 = out(vreg) _,
      ex1 = out(vreg) _,
      ex2 = out(vreg) _,
      ey0 = out(vreg) _,
      ey1 = out(vreg) _,
      ey2 = out(vreg) _,
      ax0 = out(vreg) _,
      ax1 = out(vreg) _,
      ax2 = out(vreg) _,
      ay0 = out(vreg) _,
      ay1 = out(vreg) _,
      ay2 = out(vreg) _,
      options(readonly, nostack),
    );
  }
  ([x0, x1, x2, x3, x4, x5], [y0, y1, y2, y3, y4, y5])
}
